version: '2'

services:

  backend:
    image: node
    ports:
      - 3000:3000
    command: npm start
    working_dir: /app
    volumes:
      - ./backend:/app/
    environment:
      MONGODB_URL: mongodb://mongo:27017/offers

  frontend:
    image: nginx
    working_dir: /usr/share/nginx/html
    ports:
      - 4200:80
    volumes:
      - ./frontend:/usr/share/nginx/html

  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

